name: push-main
on:
  push:
    branches:
      - main

jobs:
  docker-push:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5

      - name: zbase
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/zetaoss/zbase:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: zbase-dev
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dev
          push: true
          tags: ghcr.io/zetaoss/zbase-dev:latest
          labels: ${{ steps.meta.outputs.labels }}
